# Site settings
name: Param Shah
title: Param Shah
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://paramshah10.github.io/portfolio
baseurl: ''
email: paramshah@ucla.edu
cover: https://paramshah10.github.io/portfolio/img/og.png
logo: https://paramshah10.github.io/portfolio/img/emojis/technologist.png
resume: https://paramshah10.github.io/portfolio/resume.pdf
social:
  - title: email
    url: mailto:paramshah@ucla.edu
  - title: instagram
    url: https://instagram.com/_param__
  - title: github
    url: https://github.com/paramshah10
  - title: linkedin
    url: https://www.linkedin.com/in/paramshah10

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
